# File: docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: payroll_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: payroll_app
    restart: on-failure
    depends_on:
      - db
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - APP_PORT=${APP_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - RUN_SEEDER=${RUN_SEEDER}

volumes:
  postgres_data: